match bright:default [[:digit:]]
match bright:default [[:upper:]]
match bright:default -.
match bright:default -
match bright:default \.
match bright:default :
match bright:default \[
match bright:none \]
match bright:default (
match bright:default )
