match("bright", "[[:digit:]]")
match("punctuation", ":")
match("lowlight", "/")
match("punctuation", "\\.")
match("bright", "-")
match("bright", "_")
match("bright", "=")
match("highlight", "\\[[^]]*\\]")
