match bright:default [[:digit:]]
match punctuation:default :
match lowlight:default /
match punctuation:default \.
match bright:default -
match bright:default _
match bright:default =
match highlight:neutral \[
match highlight:default \]
