match("highlight", "yes$")
match("error", "no$")
match("highlight", "[:`'\"&]")
match("highlight", "%*%*%*")
match("lowlight", "[=%*]")
match("lowlight", "%b[]")
match("lowlight", "checking")
match("warning", "updating")
match("highlight", "creating")
match("highlight", "loading")
match("lowlight", "%(cached%)")
match("highlight", "warning: ")
match("error", "error: ")
match("error", "Error")
match("warning", "Interrupt")
