match("highlight", "yes$")
match("error", "no$")
match("punctuation", "%.")
match("punctuation", "%-")
match("punctuation", "/")
match("punctuation", "\\")
match("highlight", ":")
match("highlight", "'")
match("highlight", "`")
match("highlight", "\"")
match("highlight", "&")
match("lowlight", "=")
match("lowlight", "%[")
match("lowlight", "%]")
match("highlight", "%*%*%*")
match("lowlight", "%*")
match("lowlight", "checking")
match("warning", "updating")
match("highlight", "creating")
match("highlight", "loading")
match("punctuation", "%(cached%)")
match("highlight", "warning: ")
match("error", "error: ")
match("error", "Error")
match("warning", "Interrupt")
