if not arg["--help"] then
  match("punctuation", "%%")
  match("punctuation", "K ")
  match("punctuation", "M ")
  match("punctuation", "G ")
  match("punctuation", "T ")
  match("bright", "K-blocks")
  match("bright", "k-blocks")
  match("bright", "-blocks")
  match("bright", "Mounted on")
  match("bright", "Filesystem")
  match("bright", "Used")
  match("bright", "Available")
  match("bright", "Use%%")
  match("neutral", "%d")
  match("punctuation", "%b<>")
  match("punctuation", "%b()")
  match("punctuation", "%b[]")
  match("punctuation", "`[^']*'")
end
