if arg["--help"] then
  match("neutral", "%-")
else
  match("punctuation", "%")
  match("punctuation", "K ")
  match("punctuation", "M ")
  match("punctuation", "G ")
  match("punctuation", "T ")
  match("default", "K-blocks")
  match("default", "k-blocks")
  match("default", "-blocks")
  match("bright", "Mounted on")
end
match("neutral", "%d")
match("punctuation", "/")
match("punctuation", "%.")
match("punctuation", ":")
match("punctuation", "<")
match("punctuation", ">")
match("punctuation", "%(")
match("punctuation", "%)")
match("punctuation", "%[")
match("punctuation", "%]")
match("punctuation", "`[^']*'")
