if not arg["--help"] then
  match("punctuation", "%%")
  match("punctuation", "K ")
  match("punctuation", "M ")
  match("punctuation", "G ")
  match("punctuation", "T ")
  match("highlight", "K-blocks")
  match("highlight", "k-blocks")
  match("highlight", "-blocks")
  match("highlight", "Mounted on")
  match("highlight", "Filesystem")
  match("highlight", "Used")
  match("highlight", "Available")
  match("highlight", "Use%%")
  match("lowlight", "%d")
  match("punctuation", "%b<>")
  match("punctuation", "%b()")
  match("punctuation", "%b[]")
  match("punctuation", "`[^']*'")
end
