match highlight:default [[:digit:]]
match neutral:default :
match highlight:default `
match highlight:default '
match highlight:neutral (
match highlight:default )
match highlight:neutral \[
match highlight:default \]
match highlight:default -
