match bright:default [[:digit:]]
match neutral:default :
match bright:default /
match bright:default \[
match bright:default \]
match bright:default |
match bright:default -
match bright:default \+
match bright:none total
