if #arg > 0 and not arg["--help"] then
  match("neutral", "%d")
  match("warning", ":")
  match("neutral", "%.")
  match("neutral", "`")
  match("neutral", "'")
  match("neutral", "\"")
  match("neutral", "/")
  match("neutral", "%-")
  match("warning", "<")
  match("warning", ">")
  match("warning", "%[")
  match("warning", "%]")
  match("highlight", "warning:")
  match("error", "error:")
end
