match bright:default -
match bright:default =
match bright:default :
match bright:default /
match bright:default ,
match bright:default (
match bright:default )
match bright:default \[
match bright:default \]
