match("bright", "%.")
match("bright", ":")
match("bright", "%-")
match("bright", "%[")
match("bright", "%]")
match("bright", "%b()")
match("bright", "SOA")
match("bright", "mail is handled by")
match("bright", "name server")
match("bright", "domain name pointer")
