match("highlight", "%b[]")
match("highlight", "%b()")
match("highlight", "SOA")
match("lowlight", "mail is handled by")
match("lowlight", "name server")
match("lowlight", "domain name pointer")
match("lowlight", "has address")
