match("bright", "%b[]")
match("bright", "%b()")
match("bright", "SOA")
match("lowlight", "mail is handled by")
match("lowlight", "name server")
match("lowlight", "domain name pointer")
match("lowlight", "has address")
