match bright:default [[:digit:]]
match bright:default [[:upper:]]
match neutral:default :
match neutral:default \.
match warning:default (
match warning:default )
match bright:default \[
match bright:default \]
match highlight:default <
match highlight:default >
