match bright:default [[:digit:]]
match bright:default [[:upper:]]
match highlight:default -
match punctuation:default :
match punctuation:default \.
match punctuation:default `
match punctuation:default '
match punctuation:default \[
match punctuation:default \]
match punctuation:default (
match punctuation:default )
match highlight:none target  
