match("bright", "%d")
match("bright", "%u")
match("highlight", "%-")
match("punctuation", ":")
match("punctuation", "%.")
match("punctuation", "`")
match("punctuation", "'")
match("punctuation", "%[")
match("punctuation", "%]")
match("punctuation", "%(")
match("punctuation", "%)")
match("highlight", "target  ")
