match bright [[:digit:]]
match bright [[:upper:]]
match highlight -
match punctuation :
match punctuation \.
match punctuation `
match punctuation '
match punctuation \[
match punctuation \]
match punctuation \(
match punctuation \)
match highlight target  
