match neutral :
match punctuation -
match punctuation /
match punctuation <
match punctuation >
match punctuation \[
match punctuation \]
match error \*\*.*
match punctuation Username
match error root
