match bright:default [[:digit:]]
match bright:default '
match neutral:default :
match neutral:default \.
match neutral:default -
match neutral:default /
match neutral:default |
match neutral:default \[
match neutral:default \]
match neutral:default (
match neutral:default )
