ifnarg --interactive
match bright [[:digit:]]
match highlight :
match neutral \.
match neutral /
match neutral \[
match neutral \]
match neutral \(
match neutral \)
match warning \*
match bright -
match bright ,
match bright nmap
match highlight tcp
match warning udp
match highlight open
match warning filtered
match error closed
match neutral Port
