ifnarg --interactive
match bright:default [[:digit:]]
match highlight:default :
match neutral:default \.
match neutral:default /
match neutral:default \[
match neutral:default \]
match neutral:default (
match neutral:default )
match warning:default \*
match bright:default -
match bright:default ,
match bright:default nmap
match highlight:default tcp
match warning:default udp
match highlight:default open
match warning:default filtered
match error:default closed
match neutral:none Port
