if not arg["--help"] then
  match("bright", "[%d%.]")
  match("neutral", "/")
  match("neutral", "%[")
  match("neutral", "%]")
  match("neutral", "%(")
  match("neutral", "%)")
  match("warning", "%*")
  match("bright", ",")
  match("highlight", "tcp")
  match("warning", "udp")
  match("highlight", "open")
  match("warning", "filtered")
  match("error", "closed")
  match("neutral", "Port")
end
