match bright:default [[:digit:]]
match bright:default \.
match bright:default -
match bright:default \*
match neutral:default :
match neutral:default /
match neutral:bright \[
match neutral:default \]
match neutral:bright (
match neutral:default )
match neutral:bright {
match neutral:default }
match neutral:default \?
match neutral:default tty
match neutral:default root
