match highlight:default [[:digit:]]
match bright:default /
match highlight:default :
match highlight:default \.
match highlight:lowlight (
match highlight:default )
match highlight:lowlight \[
match highlight:default \]
match bright:none Filesystem
