match bright:default [[:digit:]]
match punctuation:default \.
match punctuation:default \[
match punctuation:default \]
match punctuation:default <
match punctuation:default >
match highlight:default {
match highlight:default }
match punctuation:default (
match punctuation:default )
match highlight:default |
match highlight:default :
match highlight:default \*
match highlight:default \+
match warning:none Kernel
match neutral:none Destination
match neutral:default default
