match("lowlight", "[|:%*%+]")
match("highlight", "[%d%.]+")
match("lowlight", "%b[]")
match("lowlight", "%b<>")
match("lowlight", "%b()")
match("highlight", "%b{}")
match("lowlight", "Destination")
match("lowlight", "default")
