match bright [[:digit:]]
match bright /
match bright \.
match highlight :
match punctuation \[
match punctuation \]
match neutral Hosts
match neutral All
match neutral Directories
match neutral Export
