match bright:default [[:digit:]]
match bright:default /
match bright:default \.
match highlight:default :
match punctuation:default \[
match punctuation:default \]
match neutral:none Hosts
match neutral:none All
match neutral:none Directories
match neutral:none Export
