match("highlight", "%d")
match("highlight", "%-")
match("highlight", "%$")
match("highlight", "%(")
match("highlight", "%)")
match("lowlight", "%[")
match("lowlight", "%]")
match("highlight", "Service")
