match("bright", "%d")
match("bright", "%u")
match("neutral", ":")
match("neutral", "%.")
match("neutral", "%(")
match("neutral", "%)")
match("neutral", "%-")
match("neutral", "`")
match("neutral", "'")
match("bright", "/")
match("bright", "%")
match("bright", " %{.}")
