match bright:default [[:digit:]]
match bright:default [[:upper:]]
match neutral:default :
match neutral:default \.
match neutral:default (
match neutral:default )
match neutral:default -
match neutral:default `
match neutral:default '
match bright:default /
match bright:default %
match bright:default  %{?}
