match("bright", "[[:digit:]]")
match("bright", "[[:upper:]]")
match("neutral", ":")
match("neutral", "\\.")
match("neutral", "\\(")
match("neutral", "\\)")
match("neutral", "-")
match("neutral", "`")
match("neutral", "'")
match("bright", "/")
match("bright", "%")
match("bright", " %\\{?\\}")
