match("bright", "%d")
match("bright", "%.")
match("bright", ":")
match("bright", "%*")
match("bright", "%(")
match("bright", "%)")
match("bright", "%b[]")
match("bright", "=")
match("bright", ",")
match("bright", " ms")
match("bright", "traceroute")
