match bright:default [[:digit:]]
match bright:default \.
match bright:default :
match bright:default *
match bright:default (
match bright:default )
match bright:bright \[
match bright:default \]
match bright:default =
